"""SQLModel persistence models registered for Alembic metadata."""

from app.models.citizen_comments import CitizenComment, CommentReport
from app.models.evidence import (
    EvidenceDerivedArtifact,
    EvidenceProcessingEvent,
    EvidenceRecord,
)
from app.models.moderation import ModerationHistory
from app.models.service_state import ServiceState
from app.models.vertical_slice import (
    CitizenIssueReport,
    CitizenReportStatusTransition,
    Claim,
    ClaimReviewRequest,
    ClaimSource,
    Contractor,
    County,
    FinancialRecord,
    Institution,
    InstitutionResponse,
    Project,
    ProjectCategory,
    ProjectContract,
    ProjectProgress,
    ProjectSubtype,
    ProjectVerification,
    ReportingChannel,
    ReportInstitutionLink,
    Source,
    SourceRecord,
    SubCounty,
    Ward,
)

__all__ = [
    "CitizenIssueReport",
    "CitizenReportStatusTransition",
    "CitizenComment",
    "CommentReport",
    "EvidenceRecord",
    "EvidenceProcessingEvent",
    "EvidenceDerivedArtifact",
    "ModerationHistory",
    "Claim",
    "ClaimReviewRequest",
    "ClaimSource",
    "Contractor",
    "County",
    "FinancialRecord",
    "Project",
    "ProjectCategory",
    "ProjectContract",
    "ProjectProgress",
    "ProjectSubtype",
    "ProjectVerification",
    "ReportingChannel",
    "Institution",
    "InstitutionResponse",
    "ReportInstitutionLink",
    "ServiceState",
    "Source",
    "SourceRecord",
    "SubCounty",
    "Ward",
]
