"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useState } from "react";
import { type Evidence, type EvidenceProcessing, downloadEvidenceFile, fetchEvidence, fetchEvidenceProcessing } from "@/lib/api";
import { EmptyState, ErrorState, Icon, LoadingSkeleton, formatDate, humanError } from "./ui";

export function EvidenceDetailPage({ id }: { id: string }) {
  const [evidence, setEvidence] = useState<Evidence>(); const [processing, setProcessing] = useState<EvidenceProcessing>(); const [error, setError] = useState<unknown>(); const [loading, setLoading] = useState(true); const [downloadError, setDownloadError] = useState<unknown>();
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const [record, process] = await Promise.all([fetchEvidence(id), fetchEvidenceProcessing(id)]); setEvidence(record); setProcessing(process); } catch (caught) { setError(caught); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const download = async () => { if (!evidence) return; setDownloadError(undefined); try { const blob = await downloadEvidenceFile(evidence.id); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = evidence.original_filename; link.click(); URL.revokeObjectURL(url); } catch (caught) { setDownloadError(caught); } };
  if (loading) return <div className="content-wrap detail-loading"><LoadingSkeleton lines={9}/></div>;
  if (error) return <div className="content-wrap page-space"><ErrorState error={error} retry={() => void load()}/></div>;
  if (!evidence) return null;
  return <div className="evidence-page"><section className="page-intro"><div className="content-wrap"><p className="eyebrow">CITIZEN-SUBMITTED EVIDENCE</p><h1>{evidence.original_filename}</h1><p>Evidence is not an official source or a verification result. Internal storage references are never shown.</p></div></section><div className="content-wrap evidence-grid"><section className="detail-section"><div className="section-heading"><h2>Evidence metadata</h2><span className="metadata-tag">{evidence.visibility}</span></div><dl className="metadata-grid"><div><dt>File type</dt><dd>{evidence.mime_type}</dd></div><div><dt>File size</dt><dd>{new Intl.NumberFormat("en-KE").format(evidence.file_size_bytes)} bytes</dd></div><div><dt>Uploaded</dt><dd>{formatDate(evidence.uploaded_at)}</dd></div><div><dt>Processing state</dt><dd>{evidence.processing_state}</dd></div><div><dt>Moderation state</dt><dd>{evidence.moderation_state}</dd></div><div><dt>Trust label</dt><dd>{evidence.trust_label.replaceAll("_", " ")}</dd></div></dl><button className="button button--dark" onClick={() => void download()}><Icon name="download" size={16}/> Download file</button>{Boolean(downloadError) && <p className="form-error">{humanError(downloadError)}</p>}</section><Processing processing={processing}/></div></div>;
}

function Processing({ processing }: { processing: EvidenceProcessing | undefined }) { return <section className="detail-section"><div className="section-heading"><h2>Processing history</h2></div>{processing ? <><p className="metadata-tag">Current state: {processing.processing_state}</p>{processing.events.length ? <ol className="timeline">{processing.events.map((event) => <li key={event.id}><i/><div><strong>{event.event_type}</strong><p>{event.from_state ?? "Start"} → {event.to_state}</p>{event.error_message && <p>{event.error_message}</p>}<small>{formatDate(event.created_at)}</small></div></li>)}</ol> : <EmptyState title="No processing events" body="The service has not published processing events for this evidence."/>}<h3 className="subheading">Derived artifacts</h3>{processing.derived_artifacts.length ? <ul className="simple-list">{processing.derived_artifacts.map((artifact) => <li key={artifact.id}><strong>{artifact.artifact_type}</strong><span>{artifact.trust_classification} · {formatDate(artifact.created_at)}</span></li>)}</ul> : <EmptyState title="No derived artifacts" body="No derived artifact lineage is currently published."/>}</> : <EmptyState title="Processing state unavailable" body="The API did not return processing information."/>}</section>; }
