"use client";

import { FormEvent, useState } from "react";
import { type ModerationHistory, fetchModerationHistory, moderate } from "@/lib/api";
import { EmptyState, ErrorState, Icon, formatDate, humanError } from "./ui";

export function ModerationPage() {
  const [target, setTarget] = useState<"comments" | "evidence">("comments"); const [id, setId] = useState(""); const [history, setHistory] = useState<ModerationHistory[]>(); const [error, setError] = useState<unknown>(); const [loading, setLoading] = useState(false);
  const inspect = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(undefined); try { setHistory(await fetchModerationHistory(target, id)); } catch (caught) { setError(caught); setHistory(undefined); } finally { setLoading(false); } };
  return <div><section className="page-intro"><div className="content-wrap"><p className="eyebrow">MODERATION</p><h1>Protected moderation workspace</h1><p>Moderation is protected by the backend’s trusted-actor boundary. CIVICACT does not provide a sign-in or token flow.</p></div></section><div className="content-wrap moderation-grid"><section className="detail-section"><h2>Find a moderation record</h2><form className="lookup-form" onSubmit={inspect}><label>Record type<select value={target} onChange={(event) => setTarget(event.target.value as "comments" | "evidence")}><option value="comments">Comment</option><option value="evidence">Evidence</option></select></label><label>Record ID<input value={id} onChange={(event) => setId(event.target.value)} placeholder="UUID" required/></label><button className="button button--dark" disabled={loading}>{loading ? "Loading…" : "View moderation history"}</button></form>{error ? <ErrorState error={error} retry={() => void inspect(new Event("submit") as unknown as FormEvent)}/> : history ? history.length ? <ol className="timeline">{history.map((entry) => <li key={entry.id}><i/><div><strong>{entry.action}</strong><p>{entry.previous_state} → {entry.resulting_state} · {entry.reason}</p><small>{formatDate(entry.created_at)}</small></div></li>)}</ol> : <EmptyState title="No moderation history" body="No protected moderation events were returned for this record."/> : <p className="form-hint">Enter a record ID to request its protected moderation history.</p>}</section><ModerationAction type={target} id={id} onComplete={() => void inspect(new Event("submit") as unknown as FormEvent)}/></div></div>;
}

function ModerationAction({ type, id, onComplete }: { type: "comments" | "evidence"; id: string; onComplete: () => void }) {
  const [action, setAction] = useState("FLAG"); const [reason, setReason] = useState("SPAM"); const [notes, setNotes] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<unknown>(); const [message, setMessage] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(undefined); setMessage(""); if (!id) { setError(new Error("Enter a record ID before taking a moderation action.")); return; } setPending(true); try { const result = await moderate(type, id, { action, reason, notes: notes || undefined }); setMessage(`${result.action} recorded. Current state: ${result.resulting_state}.`); onComplete(); } catch (caught) { setError(caught); } finally { setPending(false); } };
  return <section className="aside-card"><div className="section-heading"><h2>Moderation action</h2><Icon name="shield"/></div><p>Only configured backend moderators can submit these actions.</p><form onSubmit={submit}><label>Action<select value={action} onChange={(event) => setAction(event.target.value)}><option value="FLAG">Flag</option><option value="HIDE">Hide</option><option value="REMOVE">Remove</option><option value="RESTORE">Restore</option></select></label><label>Reason<select value={reason} onChange={(event) => setReason(event.target.value)}><option value="SPAM">Spam</option><option value="HARASSMENT">Harassment</option><option value="PERSONAL_INFORMATION">Personal information</option><option value="MALICIOUS_CONTENT">Malicious content</option><option value="INAPPROPRIATE_CONTENT">Inappropriate content</option><option value="ABUSE">Abuse</option></select></label><label>Notes <span>(optional)</span><textarea value={notes} maxLength={4000} onChange={(event) => setNotes(event.target.value)}/></label>{error && <p className="form-error">{error instanceof Error && !("status" in error) ? error.message : humanError(error)}</p>}{message && <p className="form-success">{message}</p>}<button className="button button--red button--full" disabled={pending}>{pending ? "Submitting…" : "Apply protected action"}</button></form></section>;
}
